import type {
  Home,
  Child,
  Device,
  UnknownDevice,
  SafeguardingReport,
  SafeguardingAlert,
} from "@/types";

export const homes: Home[] = [
  {
    id: "home-1",
    name: "Meadow House",
    address: "14 Oak Lane, Manchester, M1 4QR",
    router_id: "unifi-001",
    nextdns_profile_id: "ndns-abc123",
    created_at: "2025-09-01T00:00:00Z",
  },
  {
    id: "home-2",
    name: "Riverside Lodge",
    address: "7 River Street, Leeds, LS2 8HT",
    router_id: "unifi-002",
    nextdns_profile_id: "ndns-def456",
    created_at: "2025-10-15T00:00:00Z",
  },
];

export const children: Child[] = [
  { id: "child-1", initials: "AB", age: 14, home_id: "home-1", created_at: "2025-09-05T00:00:00Z" },
  { id: "child-2", initials: "CD", age: 12, home_id: "home-1", created_at: "2025-09-05T00:00:00Z" },
  { id: "child-3", initials: "EF", age: 16, home_id: "home-1", created_at: "2025-09-10T00:00:00Z" },
  { id: "child-4", initials: "GH", age: 13, home_id: "home-2", created_at: "2025-10-20T00:00:00Z" },
  { id: "child-5", initials: "IJ", age: 15, home_id: "home-2", created_at: "2025-10-20T00:00:00Z" },
];

export const devices: Device[] = [
  {
    id: "dev-1",
    name: "AB's iPhone",
    type: "phone",
    mac_address: "AA:BB:CC:11:22:33",
    child_id: "child-1",
    home_id: "home-1",
    last_connected: "2026-03-14T09:32:00Z",
    internet_enabled: true,
    schedule_start: "08:00",
    schedule_end: "20:00",
    manufacturer: "Apple",
    hostname: "ABs-iPhone",
    os_type: "iOS",
    model_prediction: "iPhone 14",
    created_at: "2025-09-06T00:00:00Z",
  },
  {
    id: "dev-2",
    name: "AB's iPad",
    type: "tablet",
    mac_address: "AA:BB:CC:44:55:66",
    child_id: "child-1",
    home_id: "home-1",
    last_connected: "2026-03-14T08:15:00Z",
    internet_enabled: true,
    schedule_start: null,
    schedule_end: null,
    manufacturer: "Apple",
    hostname: "ABs-iPad",
    os_type: "iPadOS",
    model_prediction: "iPad Air",
    created_at: "2025-09-06T00:00:00Z",
  },
  {
    id: "dev-3",
    name: "CD's Samsung",
    type: "phone",
    mac_address: "DD:EE:FF:11:22:33",
    child_id: "child-2",
    home_id: "home-1",
    last_connected: "2026-03-14T10:05:00Z",
    internet_enabled: true,
    schedule_start: "08:00",
    schedule_end: "19:00",
    manufacturer: "Samsung",
    hostname: "Galaxy-S23",
    os_type: "Android",
    model_prediction: "Galaxy S23",
    created_at: "2025-09-07T00:00:00Z",
  },
  {
    id: "dev-4",
    name: "EF's Laptop",
    type: "laptop",
    mac_address: "11:22:33:AA:BB:CC",
    child_id: "child-3",
    home_id: "home-1",
    last_connected: "2026-03-13T22:10:00Z",
    internet_enabled: false,
    schedule_start: "09:00",
    schedule_end: "21:00",
    manufacturer: "HP",
    hostname: "HP-Pavilion",
    os_type: "Windows",
    model_prediction: "HP Pavilion 15",
    created_at: "2025-09-11T00:00:00Z",
  },
  {
    id: "dev-5",
    name: "GH's Phone",
    type: "phone",
    mac_address: "44:55:66:DD:EE:FF",
    child_id: "child-4",
    home_id: "home-2",
    last_connected: "2026-03-14T07:45:00Z",
    internet_enabled: true,
    schedule_start: "07:00",
    schedule_end: "20:00",
    manufacturer: "Apple",
    hostname: "GHs-iPhone",
    os_type: "iOS",
    model_prediction: "iPhone 13",
    created_at: "2025-10-21T00:00:00Z",
  },
];

export const unknownDevices: UnknownDevice[] = [
  {
    id: "unknown-1",
    mac_address: "FF:AA:BB:CC:DD:01",
    manufacturer: "Samsung",
    device_type: "Phone",
    first_detected: "2026-03-14T06:22:00Z",
    home_id: "home-1",
    blocked: true,
  },
  {
    id: "unknown-2",
    mac_address: "FF:AA:BB:CC:DD:02",
    manufacturer: "Unknown",
    device_type: null,
    first_detected: "2026-03-14T03:14:00Z",
    home_id: "home-1",
    blocked: true,
  },
];

export const reports: SafeguardingReport[] = [
  {
    id: "report-1",
    child_id: "child-1",
    child_initials: "AB",
    device_name: "AB's iPhone",
    category: "gambling",
    domain: "bet365.com",
    action: "blocked",
    timestamp: "2026-03-14T21:14:00Z",
    home_id: "home-1",
  },
  {
    id: "report-2",
    child_id: "child-1",
    child_initials: "AB",
    device_name: "AB's iPhone",
    category: "gambling",
    domain: "williamhill.com",
    action: "blocked",
    timestamp: "2026-03-14T21:18:00Z",
    home_id: "home-1",
  },
  {
    id: "report-3",
    child_id: "child-1",
    child_initials: "AB",
    device_name: "AB's iPad",
    category: "gambling",
    domain: "paddypower.com",
    action: "blocked",
    timestamp: "2026-03-14T21:25:00Z",
    home_id: "home-1",
  },
  {
    id: "report-4",
    child_id: "child-3",
    child_initials: "EF",
    device_name: "EF's Laptop",
    category: "proxy_vpn",
    domain: "nordvpn.com",
    action: "blocked",
    timestamp: "2026-03-13T22:05:00Z",
    home_id: "home-1",
  },
  {
    id: "report-5",
    child_id: "child-2",
    child_initials: "CD",
    device_name: "CD's Samsung",
    category: "adult_content",
    domain: "explicit-site.com",
    action: "blocked",
    timestamp: "2026-03-13T20:44:00Z",
    home_id: "home-1",
  },
  {
    id: "report-6",
    child_id: "child-1",
    child_initials: "AB",
    device_name: "AB's iPhone",
    category: "gambling",
    domain: "betfair.com",
    action: "blocked",
    timestamp: "2026-03-14T21:30:00Z",
    home_id: "home-1",
  },
  {
    id: "report-7",
    child_id: "child-1",
    child_initials: "AB",
    device_name: "AB's iPhone",
    category: "gambling",
    domain: "skybet.com",
    action: "blocked",
    timestamp: "2026-03-14T21:42:00Z",
    home_id: "home-1",
  },
  {
    id: "report-8",
    child_id: "child-4",
    child_initials: "GH",
    device_name: "GH's Phone",
    category: "violence",
    domain: "violent-content.com",
    action: "blocked",
    timestamp: "2026-03-14T15:30:00Z",
    home_id: "home-2",
  },
];

export const alerts: SafeguardingAlert[] = [
  {
    id: "alert-1",
    child_initials: "AB",
    category: "gambling",
    timestamp: "2026-03-14T21:42:00Z",
    home_id: "home-1",
    type: "pattern",
    details: "5 gambling attempts within 24 hours",
    attempts: 5,
  },
  {
    id: "alert-2",
    child_initials: "AB",
    category: "gambling",
    timestamp: "2026-03-14T21:14:00Z",
    home_id: "home-1",
    type: "single",
  },
  {
    id: "alert-3",
    child_initials: "EF",
    category: "proxy_vpn",
    timestamp: "2026-03-13T22:05:00Z",
    home_id: "home-1",
    type: "single",
  },
  {
    id: "alert-4",
    child_initials: "CD",
    category: "adult_content",
    timestamp: "2026-03-13T20:44:00Z",
    home_id: "home-1",
    type: "single",
  },
];
